# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
wedding = Wedding.new(groom_name: "Diego Mesi", bride_name: "Sandra Brandariz")
wedding.save
groom = Groom.new({username: "Diego", password: "lopezbrandariz",description: "El novio"})
groom.wedding = wedding
groom.save
bride = Bride.new({username: "Sandra", password: "mondarizmesia",description: "La novia"})
bride.wedding = wedding
bride.save

guests = [
            {username: "Anxo",password: "Padre",description: "Padre de Diego"}, 
            {username: "Fe",password: "Madre",description: "Madre de Diego"}, 
            {username: "Álvaro",password: "OiAlvarin",description: "Hermano mayor de Diego"}, 
            {username: "Minia",password: "ColleORamo",description: "Novia de Álvaro, hermano de Diego"}, 
            {username: "Andrés",password: "Tuto",description: "Tí­o de Diego"}, 
            {username: "Angelina",password: "Tuta",description: "Tí­a de Diego"}, 
            {username: "Virginia",password: "Mamao",description: "Abuela materna de Diego"}, 
            {username: "Andrea",password: "Tostaduca",description: "Prima de Diego"}, 
            {username: "Quico",password: "Mentalista",description: "Primo de Diego, Beealia.com"}, 
            {username: "David",password: "VividorJalador",description: "Primo de zumosol de Diego"}, 
            {username: "Liso",password: "Campobello",description: "Tío de Diego"}, 
            {username: "Macu",password: "CochaBrava",description: "Tía de Diego"}, 
            {username: "Rebeca",password: "Acabeeeei",description: "Prima eslovaca de Diego"}, 
            {username: "Adrián",password: "CamisaNaranja",description: "Casi-primo de Diego, novio de Rebeca"}, 
            {username: "Luis",password: "Toleiran",description: "Tío tolo de Diego, Fleire.com"}, 
            {username: "Mari Luz",password: "UnKiloDeMacarrois",description: "Tía de Diego"}, 
            {username: "Nerea",password: "NooonTenhoFrio",description: "Prima pequeña de Diego, artista musical de nacimiento"}, 
            {username: "Avelina",password: "AbuelaAvelina",description: "Abuela paterna de Diego"}, 
            {username: "Eugenio",password: "Eugenio",description: "Tío de Diego"}, 
            {username: "Mary",password: "TiaMary",description: "Tía de Diego"}, 
            {username: "Pereiro",password: "FcBarcelona",description: "Tío de Diego"}, 
            {username: "Gabi",password: "WalterWhite",description: "Primo de Diego"}, 
            {username: "Chiní­n",password: "NegroCatalan",description: "Primo de Diego, chino-negro para los amigos"}, 
            {username: "Mónica",password: "NoviaDelNegroCatalan",description: "Casi-prima de Diego, novia de chinín"}, 
            {username: "Ángeles",password: "TiaFashion",description: "Tía de Diego"}, 
            {username: "Miguel",password: "HAIQUEIRBANHARSEAORIO",description: "Tío de Diego"}, 
            {username: "Moisés",password: "MilPeinados",description: "Primo fashion de Diego"}, 
            {username: "Paz",password: "MADRINADIEGO",description: "Madrina de Diego"}, 
            {username: "Rogelio",password: "PADRINODIEGO",description: "Padrino de Diego"}, 
            {username: "Jacobo",password: "Beches",description: "DJ de la boda y primo de Diego"}, 
            {username: "Lucí­a",password: "PrimaBeches",description: "Casi-prima de Diego, novia del DJ"}, 
            {username: "Noelia",password: "MamiDelPrincipito",description: "Prima de Diego"}, 
            {username: "Dani",password: "PapiDelPrincipito",description: "Primo de Diego"}, 
            {username: "Aitor",password: "Principito",description: "Niño de arras, hijo de Noelia y Dani"}, 
            {username: "Natalia",password: "ProfeDeLaCoru",description: "Prima de Diego"}, 
            {username: "Lucita",password: "Lucita",description: "Familiar de Diego"}, 
            {username: "Argimino",password: "Argimino",description: "Familiar de Diego"}, 
            {username: "Begoña",password: "Begonha",description: "Familiar de Diego"}, 
            {username: "López",password: "3334",description: "Socio y amigo de Diego"}, 
            {username: "Tito",password: "Ibagaza",description: "Socio y amigo de Diego"}, 
            {username: "Laura",password: "PrimitivoCurrantez",description: "Novia de Tito"}, 
            {username: "Dani",password: "DePuntoRegos",description: "Amigo de Diego"}, 
            {username: "Borjita",password: "BarjitaNait",description: "Amigo de Diego, propietario de media Sarria nocturna"}, 
            {username: "Sanmartín",password: "EsperaUnMomentoJoseManuel",description: "Amigo de Diego, propietario del coche de entrada"}, 
            {username: "Kenya",password: "NoviaDeSanMartin",description: "Acompañante de Sanmartín, natural de Maspalomas"}, 
            {username: "Pablo",password: "FrikiMakei",description: "Amigo de Diego"}, 
            {username: "Sandra",password: "MujerDelFrikiMakei",description: "Mujer de Pablo, amigo de Diego"}, 
            {username: "Nando",password: "JosebaBeloki",description: "Amigo de Diego, se parece a Novita de Doraemon"}, 
            {username: "Noelia",password: "MiticaNoviaDeNando",description: "Novia de Nando"}, 
            {username: "Franqueira",password: "VasoDeTubo",description: "Amigo de Diego, futbolista franquicia del CD Mesía"}, 
            {username: "Marta",password: "SiFumasDivorcio",description: "Mujer de Diego Franqueira"}, 
            {username: "Lidia",password: "lidia",description: "Amiga de Diego y Sandra"}, 
            {username: "César",password: "cesar",description: "Amigo de Diego y Sandra"}, 
            {username: "David Fergasa",password: "ChinaNegraRubia",description: "Amigo de Diego, propietario del coche de entrada"}, 
            {username: "Daproxa",password: "Brother",description: "Amigo de Diego, flamante capitán y principal cabeza visible del CD Mesía"}, 
            {username: "Eva",password: "VaiaCochazoMeGasto",description: "Novia de Manuel Daproxa"}, 
            {username: "Miguelón",password: "Migallas",description: "Amigo de Diego, se parece a Xigante de Doraemon"}, 
            {username: "Kaky",password: "Kakyterapia",description: "Amigo de Diego, delantero incisivo"}, 
            {username: "Breo",password: "CagocheNaPortaCampeleiro",description: "Amigo de Diego, director deportivo del CD Mesía"}, 
            {username: "Awa",password: "NoviaBreo",description: "Novia de Breo"}, 
            {username: "Jonzales",password: "Yonza",description: "Amigo de Diego, mvp en la despedida"}, 
            {username: "Torrixo",password: "RomanoSion",description: "Amigo de Diego, proviene de Tailandia"}, 
            {username: "Jorge",password: "Xurxo",description: "Amigo de Diego, arquitecto"}, 
            {username: "Nuria",password: "NuriaDeXurxo",description: "Novia de Jorge do Pazo"}, 
            {username: "Dani Fraga",password: "Domedico",description: "Amigo de Diego, doctor"}, 
            {username: "Sandra Dani Fraga",password: "NoviaDomedico",description: "Novia de Dani Fraga"}, 
            {username: "Ví­ctor Valiña",password: "DobleV",description: "Amigo de Diego, CD Mesía's physical trainer"}, 
            {username: "Mónica",password: "Ibiza",description: "Novia de Víctor Valiña"}, 
            {username: "Campelo",password: "Campelo",description: "Amigo de Diego, sólo Dios le juzga"}, 
            {username: "Montis",password: "FomorDeFesta",description: "Amigo de Diego, lateral izquierdo de garantías del CD Mesía"}, 
            {username: "Fran de Sesto",password: "BarroLamaUuuuu",description: "Amigo de Diego, lateral derecho de garantías del CD Mesía"}, 
            {username: "Pardo",password: "invitado1",description: "Amigo de Diego, jefazo del CD Mesía"}, 
            {username: "Sabino",password: "invitado2",description: "Amigo de Diego, máximo accionista del CD Mesía"}, 
            {username: "Vales",password: "invitado3",description: "Amigo de Diego, presi del CD Mesía"}, 
            {username: "Mari Carmen",password: "AiJoseLevameAMochila",description: "Amiga de Ángel y Fe"}, 
            {username: "José Antonio",password: "LevaaiTuNaTrouxeras",description: "Amigo de Ángel y Fe"}, 
            {username: "David de Fazouro",password: "Vaia",description: "Amigo de Diego, parecido a Arizmendi y a Cuenca"}, 
            {username: "Pablo de Fazouro",password: "FaceranUnPuente",description: "Amigo de Diego, veraneaba en Mesía en sus tiempos mozos"}, 
            {username: "Emma",password: "NoviaDePabloLugo",description: "Novia de Pablo"}, 
            {username: "Alberto",password: "DonQuijote",description: "Amigo de Ángel y Fe, se parece a Don Quijote"}, 
            {username: "Alicia",password: "AliciaDonQuijote",description: "Amiga de Ángel y Fe"}, 
            {username: "Fraga",password: "OMedico",description: "Amigo de Ángel y Fe"}, 
            {username: "Carmen",password: "AMullerDoMedico",description: "Amiga de Ángel y Fe"}, 
            {username: "Eduardo",password: "Edu",description: "Amigo de Diego"}, 
            {username: "Quique",password: "BarKike",description: "Amigo de Ángel y Fe"}, 
            {username: "Julia",password: "TortillaDeTresPisos",description: "Amiga de Ángel y Fe"}, 
            {username: "Roberto",password: "CanDePresa",description: "Amigo de Diego, eterno capitán del CD Mesía"}, 
            {username: "Sandra",password: "MullerCanDePresa",description: "Mujer de Roberto de Mesía"}, 
            {username: "Noela",password: "NenaCanDePresa",description: "Hija de Roberto y Sandra"}, 
            {username: "Manuel Enrique",password: "LuisFigoDoMesia",description: "Amigo de Diego, gran ex-interior derecho y gran tenista"}, 
            {username: "Joaquín",password: "Molina",description: "Amigo de Diego, muy fan de Arizmendi"}, 
            {username: "Emilia",password: "Albaricoques",description: "Mujer de JoaquÃín"}, 
            {username: "Mari Luz do Fleire",password: "MariLuzFleire",description: "Familiar materno de Diego"}, 
            {username: "Enrique",password: "EnriqueDeBusgardin",description: "Familiar materno de Diego"}, 
            {username: "Mercedes",password: "MercedesDeBusgardin",description: "Familiar materno de Diego"}, 
            {username: "Lorenzo",password: "LorenzoDeBusgardin",description: "Familiar materno de Diego"}, 
            {username: "Carmen",password: "CarmenDeBusgardin",description: "Familiar materno de Diego"}, 
            {username: "Laura",password: "LauraDeBusgardin",description: "Familiar materno de Diego"}, 
            {username: "Antonio",password: "AntonioDeBusgardin",description: "Familiar materno de Diego"}, 
            {username: "Pichuchi",password: "VivaEspanha",description: "Amigo de Diego, en busca y captura"}, 
            {username: "Eudaldo",password: "Eudaldo",description: "Amigo de Ángel y Fe"}, 
            {username: "Loli",password: "Loli",description: "Amiga de Ángel y Fe"}, 
            {username: "Juan",password: "Somorostro",description: "Amigo de Ángel y Fe"}, 
            {username: "Angeles",password: "MujerDelSomorostro",description: "Amiga de Ángel y Fe"}, 
            {username: "Rober",password: "Tocha",description: "Amigo de Diego y Sandra, entrenador del CD Mesía"}, 
            {username: "Miriam",password: "Happy",description: "Amiga de Diego y Sandra, mujer de Rober Iglesias"}, 
            {username: "Iago",password: "Sempiterno",description: "Amigo de Diego y Sandra, posiblemente las piernas más trencas de toda la boda"}, 
            {username: "Marta",password: "PaddelPro",description: "Amiga de Diego y Sandra, novia de Iago Iglesias"}, 
            {username: "Abelleira",password: "CabezaPinha",description: "Amigo de Diego y Sandra, kaiser del CD Mesía y gran conocedor del mundo de la cocina en lo que a muebles se refiere"}, 
            {username: "Rebeca",password: "ChicaSfera",description: "Amiga de Diego y Sandra, novia de Abelleira"}, 
            {username: "Marcos",password: "Marcoitos",description: "Amigo de Diego y Sandra, estrenando matrimonio con Ana"}, 
            {username: "Ana",password: "AnaMarcos",description: "Amiga de Diego y Sandra, estrenando matrimonio con Marcos Iglesias"}, 
            {username: "Rubén",password: "Cachuli",description: "Amigo de Diego y Sandra, el más enclenque de toda la boda"}, 
            {username: "Cris",password: "Doctora",description: "Amiga de Diego y Sandra, novia de Rubén Ponte"}, 
            {username: "Mery Abelleira",password: "RecienMama",description: "Amiga de Diego y Sandra, hermana de Abelleira"}, 
            {username: "Carlos",password: "RecienPapa",description: "Amigo de Diego y Sandra, marido de Mery Abelleira"}, 
            {username: "Isa",password: "VivaMontealto",description: "Amiga de Diego y Sandra, vela por la seguridad de la capilla"}, 
            {username: "Brais",password: "FestaNoDux",description: "Amigo de Diego y Sandra, vive por y para Enxendra"}, 
            {username: "Mar",password: "EstrellaGalicia",description: "Amiga de Diego y Sandra, novia de Brais"}, 
            {username: "Josuke",password: "GranDisenhadorMejorPersona",description: "Amigo de Diego y Sandra, responsable de las invitaciones y del diseño de los muñecos, un artista!"}, 
            {username: "Noemí",password: "NoemiJosuke",description: "Amiga de Diego y Sandra, novia de Josuke"}, 
            {username: "Rafa",password: "DaleAlTimon",description: "Amigo de Diego, Torasa es su pasión"}, 
            {username: "Raúl",password: "Pelao",description: "Amigo de Diego, seguirá marcando goles hasta los 50 años"}, 
            {username: "Pablo Martí­nez",password: "Becerrito",description: "Amigo de Diego, de delantero a central en nada, qué bonito es el fútbol"}, 
            {username: "Jorge Rebollo",password: "Peztillo",description: "Amigo de Diego, reciente fichaje del Silva, próximo fichaje del CD Mesía"}, 
            {username: "Leticia",password: "LetiPeztillo",description: "Novia de Jorge Rebollo"}, 
            {username: "Inés",password: "LaPreferidaParaDavid",description: "Amiga de Diego y Sandra, lucense"}, 
            {username: "Mart­a",password: "Puerto",description: "Amiga de Diego y Sandra, lucense"}, 
            {username: "Alba",password: "AlbaPIR",description: "Amiga de Diego y Sandra, lucense"}, 
            {username: "Moncho",password: "Moncho",description: "Amigo de Diego y Sandra, más mítico en Lugo que la muralla"}, 
            {username: "Galdo",password: "Galdo",description: "Amigo de Diego y Sandra, sin la batería de su móvil no existiría este evento"}, 
            {username: "Julián",password: "RobsonDeSousa",description: "Amigo de Diego y Sandra, nervioso de nacimiento, en sisas en San Froilán"}, 
            {username: "Muiña",password: "PeterCrouch",description: "Amigo de Diego y Sandra, parece bielorruso pero es de Lugo"}, 
            {username: "Nachito",password: "Nachito",description: "Amigo de Diego y Sandra, action man "}, 
            {username: "Laurita",password: "LauritaNachito",description: "Amiga de Diego y Sandra, novia de Nachito"}, 
            {username: "Óscar Trujas",password: "Trujas",description: "Amigo de Diego y Sandra, las motos su pasión"}, 
            {username: "José",password: "PapyFergasa",description: "Amigo de Diego y Sandra, propietario del cochazo más antiguo de la entrada"}, 
            {username: "Carmen",password: "MamyFergasa",description: "Amiga de Diego y Sandra, propietaria del cochazo más antiguo de la entrada"}, 
            {username: "Suso ",password: "Papy ",description: "Padre de Sandra"}, 
            {username: "Nanda",password: "Mamy",description: "Madre de Sandra"}, 
            {username: "Abuela",password: "Abuelita",description: "Abuela materna de Sandra"}, 
            {username: "Alby",password: "Alby",description: "Hermana de Sandra"}, 
            {username: "Jorge",password: "CunhyYoguini",description: "Marido de Alba, hermana de Sandra"}, 
            {username: "Pablo",password: "Pablete",description: "Niño de arras e hijo de Alba y Jorge"}, 
            {username: "Manolo",password: "Tioguay",description: "Tío guay de Sandra"}, 
            {username: "Ana",password: "Tiaguay",description: "Tío guay de Sandra"}, 
            {username: "Manuel",password: "DetectiveManuel",description: "Primo detective de Sandra"}, 
            {username: "Uxía",password: "MiniSandra",description: "Niña de arras y prima de Sandra"}, 
            {username: "Abuela Pura",password: "AbuelaPura",description: "Abuela paterna de Sandra"}, 
            {username: "Alba",password: "TiaAlba",description: "Tía paterna de Sandra"}, 
            {username: "Gonzalo",password: "Gon",description: "Tío paterno de Sandra"}, 
            {username: "Tonecho",password: "TioTonecho",description: "Primo de Sandra"}, 
            {username: "LucÃ­a",password: "PrimaLoca",description: "Prima de Sandra"}, 
            {username: "Edgar",password: "NovioDeLaPrimaLoca",description: "Novio de Lucía, prima de Sandra"}, 
            {username: "Tonechito",password: "Esterko",description: "Primo de Sandra"}, 
            {username: "Novia Tonechito",password: "AcompanhanteDeTonechito",description: "Novia de Tonechito, primo de Sandra"}, 
            {username: "Laurita",password: "PrimaLaurita",description: "Prima de Sandra"}, 
            {username: "Adriana",password: "PrimaAdri",description: "Prima de Sandra"}, 
            {username: "Jorge",password: "FuturoMaridoDeLaPrimaAdri",description: "Novio de Adriana, prima de Sandra"}, 
            {username: "Isa",password: "PrimaIsa",description: "Prima de Sandra"}, 
            {username: "Rafa",password: "ParejaDeLaPrimaIsa",description: "Primo de Sandra"}, 
            {username: "Yenco",password: "PrimoYenco",description: "Primo de Sandra"}, 
            {username: "Patricia",password: "MujerDelPrimoYenco",description: "Mujer de Yenco, prima de Sandra"}, 
            {username: "José Ãngel",password: "PrimoJoseAngel",description: "Primo de Sandra"}, 
            {username: "Ana",password: "MujerDelPrimoJosÃ©Ãngel",description: "Mujer de José Ángel, primo de Sandra"}, 
            {username: "Maño",password: "Manho",description: "Hermano de Abuela Pura"}, 
            {username: "María",password: "Mari­aDeManho",description: "Mujer del hermano de Abuela Pura"}, 
            {username: "Mañuco",password: "PrimoMahuco",description: "Primo de Sandra"}, 
            {username: "David",password: "PrimoDavid",description: "Primo de Sandra"}, 
            {username: "Zeltia",password: "MujerDelPrimoDavid",description: "Mujer de David, primo de Sandra"}, 
            {username: "Manolito Remi",password: "Manolito",description: "Ahijado de Suso, el padre de Sandra"}, 
            {username: "Pili",password: "PiliManolito",description: "Mujer de Manolito Remi"}, 
            {username: "Martín",password: "Martin",description: "Familiar de Sandra"}, 
            {username: "Estrellita",password: "Estrellita",description: "Familiar de Sandra"}, 
            {username: "Evaristo",password: "Evaristo",description: "Familiar de Sandra"}, 
            {username: "Fina",password: "FinaEvaristo",description: "Familiar de Sandra"}, 
            {username: "Tí­a Carmen",password: "TiaCarmen",description: "Familiar de Sandra"}, 
            {username: "Valeriano",password: "Valeriano",description: "Familiar de Sandra"}, 
            {username: "Mari Carmen",password: "MariCarmen",description: "Familiar de Sandra"}, 
            {username: "Oscar ",password: "PrimoOscar",description: "Primo de Sandra"}, 
            {username: "Bernardita",password: "Bernardita",description: "Familiar de Sandra"}, 
            {username: "TiaLola",password: "TiaLola",description: "Familiar de Sandra"}, 
            {username: "TiaManolita",password: "TiaManolita",description: "Familiar de Sandra"}, 
            {username: "TioLuis",password: "TioLuis",description: "Familiar de Sandra"}, 
            {username: "Rubén",password: "PrimoRuben",description: "Familiar de Sandra"}, 
            {username: "Marga",password: "NoviaDelPrimoRubÃ©n",description: "Familiar de Sandra"}, 
            {username: "Inés",password: "PrimaInes",description: "Familiar de Sandra"}, 
            {username: "Marido - Fran",password: "MaridoDeInes",description: "Familiar de Sandra"}, 
            {username: "José",password: "JoseDoPenhasco",description: "Amigo de Sandra y Diego"}, 
            {username: "Elena",password: "ElenaDoPenhasco",description: "Amiga de Sandra y Diego"}, 
            {username: "Dani",password: "DaniDoPenhasco",description: "Amigo de Sandra y Diego"}, 
            {username: "Vanesa",password: "VanesaCasiDoPenhasco",description: "Amiga de Sandra y Diego"}, 
            {username: "Manolita Fuenteculler",password: "ManolitaFuenteculler",description: "Familiar de Sandra"}, 
            {username: "Mary",password: "Mary",description: "Familiar de Sandra"}, 
            {username: "Noela",password: "Noela",description: "Familiar de Sandra"}, 
            {username: "Toño",password: "Tonho",description: "Familiar de Sandra"}, 
            {username: "Brais",password: "Brais",description: "Familiar de Sandra"}, 
            {username: "Natalia",password: "MejorAmiga",description: "Amiga de Sandra"}, 
            {username: "David",password: "NovioDeMejorAmiga",description: "Novio de Natalia, amiga de Sandra"}, 
            {username: "Lucía",password: "LucÃ­aGeox",description: "Amiga de Sandra"}, 
            {username: "Hugo",password: "NovioDeLuciaGeox",description: "Novio de Lucía, amiga de Sandra"}, 
            {username: "Cristina Nos",password: "AmigaGenial",description: "Amiga de Sandra"}, 
            {username: "Noureddine",password: "NovioDeAmigaGenial",description: "Novio de Cristina, amiga de Sandra"}, 
            {username: "María",password: "MariaFriki",description: "Amiga de Sandra"}, 
            {username: "Fer",password: "NovioDeMariaFriki",description: "Novio de María, amiga de Sandra"}, 
            {username: "Almudena",password: "almugrey",description: "Amiga de Sandra"}, 
            {username: "Ramón",password: "NovioDeAlmuGrey",description: "Novio de Almudena, amiga de Sandra"}, 
            {username: "Inés",password: "Inesuka",description: "Amiga de Sandra"}, 
            {username: "Paula",password: "Pauli",description: "Amiga de Sandra"}, 
            {username: "Jose",password: "NovioDePauli",description: "Novio de Paula, amiga de Sandra"}, 
            {username: "Adriana",password: "AdrianaPelu",description: "Amiga de Sandra"}, 
            {username: "César",password: "NovioDeAdrianaPelu",description: "Novio de Sandra, amiga de Adriana"}, 
            {username: "Silvia",password: "CastelaoCanarias",description: "Amiga de Sandra"}, 
            {username: "Rubén",password: "RubenCarral",description: "Novio de Silvia, amiga de Sandra"}, 
            {username: "Eva",password: "MeCaso",description: "Amiga de Sandra"}, 
            {username: "Martí­n",password: "Yotambien",description: "Novio de Eva, amiga de Sandra"}, 
            {username: "Mary",password: "MarySada",description: "Familiar de Sandra"}, 
            {username: "Jorge",password: "JorgeSada",description: "Familiar de Sandra"}, 
            {username: "Pepiño",password: "PepinhoSada",description: "Familiar de Sandra"}, 
            {username: "Juan Sada",password: "JuanSada",description: "Familiar de Sandra"}, 
            {username: "Pablo",password: "PabloSada",description: "Familiar de Sandra"}, 
            {username: "Carolina",password: "CarolSada",description: "Familiar de Sandra"}, 
            {username: "Tía Maruja",password: "TiaMaruja",description: "Familiar de Sandra"}, 
            {username: "María",password: "MadrinaSandra",description: "Madrina de Sandra"}, 
            {username: "Carlos",password: "PadrinoSandra",description: "Padrino de Sandra"}, 
            {username: "Sonia",password: "SoniaMujerDePadrino",description: "Mujer del padrino de Sandra"}, 
            {username: "Samuel",password: "PrimoSamuel",description: "Primo de Sandra"}, 
            {username: "Tí­o José",password: "TioJose",description: "Tío abuelo de Sandra"}, 
            {username: "Edelmira",password: "TiaEdelmira",description: "Tía abuela de Sandra"}, 
            {username: "Jorge",password: "JorgeBalado",description: "Primo de Sandra"}, 
            {username: "Manoli",password: "ManoliBalado",description: "Mujer del primo de Sandra"}, 
            {username: "Estela",password: "EstelaBalado",description: "Prima de Sandra"}, 
            {username: "Xos",password: "XosBalado",description: "Primo de Sandra"}, 
            {username: "Carlos",password: "CarlosBalado",description: "Primo de Sandra"}, 
            {username: "Irene",password: "IreneBalado",description: "Prima de Sandra"}, 
            {username: "Ana",password: "-",description: "Prima de Sandra"}, 
            {username: "Mateo",password: "-",description: "Primo de Sandra"}, 
            {username: "Víctor",password: "Victor",description: "Primo de Sandra"}, 
            {username: "Belén",password: "Belen",description: "Prima de Sandra"}, 
            {username: "Lidia",password: "Lidia",description: "Prima de Sandra"}, 
            {username: "Lucía",password: "Lucia",description: "Prima de Sandra"}, 
            {username: "Manolo",password: "ManoloBalado",description: "Familiar de Sandra"}, 
            {username: "Elisa",password: "ElisaBalado",description: "Familiar de Sandra"}, 
            {username: "Manolo Santa Cruz",password: "ManoloDeSantaCruz",description: "Familiar de Sandra"}, 
            {username: "Maruja",password: "MarujaDeSantaCruz ",description: "Familiar de Sandra"}, 
            {username: "Angela",password: "AngelaDeSantaCruz",description: "Prima de Sandra"}, 
            {username: "Marcos",password: "MarcosDeSantaCruz",description: "Primo de Sandra"}, 
            {username: "Sandra",password: "ProfePrimaSandra",description: "Prima de Sandra"}, 
            {username: "Manolo",password: "MaridoDeLaProfeSandra",description: "Marido de la prima de Sandra, Sandra"}, 
            {username: "Maruja Parada",password: "MarujaDeParada",description: "Familiar de Sandra"}, 
            {username: "Paco",password: "PacoDeParada",description: "Familiar de Sandra"}, 
            {username: "Susana",password: "SusanaDeParada",description: "Familiar de Sandra"}, 
            {username: "Alfonso",password: "Alfonso",description: "Familiar de Sandra"}, 
            {username: "Mari Carmen",password: "MariCarmenAlfonso",description: "Familiar de Sandra"}, 
            {username: "Vanesa",password: "ProfeVanesa",description: "Prima de Sandra"}, 
            {username: "Jhonny",password: "ProfeJhonny",description: "Novio de Vanesa, prima de Sandra"}, 
            {username: "Chus",password: "ProfeChusJuntasForever",description: "Amiga de Sandra"}, 
            {username: "Antonio",password: "MaridoDeLaProfeChus",description: "Marido de Chus, amiga de Sandra"}, 
            {username: "Nieves",password: "ProfeNievesJuntasForever",description: "Amiga de Sandra"}, 
            {username: "Marido",password: "MaridoDeLaProfeNieves",description: "Marido de Nieves, amiga de Sandra"}, 
            {username: "Laura",password: "LauraNieves",description: "Amiga de Sandra"}, 
            {username: "Antonio",password: "ElAlboradaTeExtranhara",description: "Amigo de Sandra"}, 
            {username: "Mujer Antonio",password: "MujerDelProfeAntonio",description: "Mujer de Antonio, amigo de Sandra"}, 
            {username: "Silvia Bouza",password: "SilviaBouzaGranAmiga",description: "Amiga de Sandra"}, 
            {username: "Mari Carmen",password: "MariCarmenRecreo",description: "Familiar de Sandra"}, 
            {username: "María",password: "MarÃ­aRecreo",description: "Familiar de Sandra"}, 
            {username: "Guillermo Mito",password: "Mito",description: "Familiar de Sandra"}, 
            {username: "Mujer Guillermo ",password: "MujerDeMito",description: "Familiar de Sandra"}, 
            {username: "Salomé",password: "SalomeRecreo",description: "Familiar de Sandra"}, 
            {username: "Carlos",password: "CarlosRecreo",description: "Familiar de Sandra"}, 
            {username: "Samuel ",password: "SamuelRecreo",description: "Familiar de Sandra"}, 
            {username: "Andrea",password: "ProfeAndrea",description: "Amiga de Sandra"}, 
            {username: "Iris",password: "Iris",description: "Amiga de Sandra"}, 
            {username: "Mari",password: "MariAmigaDeLaAbuelaPura",description: "Familiar de Sandra"}, 
            {username: "Any",password: "any",description: "Amiga de Sandra"}, 
            {username: "Marido de Any",password: "maridodeany",description: "Marido de Any, amiga de Sandra"}, 
            {username: "Andrea",password: "andrea",description: "Amiga de Sandra"}, 
            {username: "Chris",password: "chris",description: "Amigo de Sandra"}
        ]

guests.each do |g|
    guest = Guest.new(g)
    guest.wedding = wedding
    guest.save
end
